/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package canoa_123.views;

import canoa_123.Controller.DAO.ExceptionDAO;
import canoa_123.Controller.PassageirosController;
import canoa_123.Models.Passageiros;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author °°Felipe°°Lael°°
 */
public class TelaConsultaPassageiros extends javax.swing.JPanel {

    private Object telacadastrarpassageiros;

    /**
     * Creates new form TelaConsultaPassageiros
     */
    public TelaConsultaPassageiros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesqPas = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPassageiro = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Consultar Passageiros");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Passageiro:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btnPesqPas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPesqPas.setText("Pesquisar");
        btnPesqPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqPasActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblPassageiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "CPF", "TELEFONE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPassageiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPassageiroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPassageiro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesqPas)
                        .addGap(160, 160, 160))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnPesqPas)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnPesqPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqPasActionPerformed

        String nome = txtNome.getText();
        DefaultTableModel tableModel = (DefaultTableModel) tblPassageiro.getModel(); // SEMPRE QUE CRIAR UMA TABELA, PRECISA INSTANCIAR
        tableModel.setRowCount(0); // zera as linhas da tabela, sempre que fizer uma pesquisa, se nao colocar ele deixa todas as linhas das consultas interiores, se colocar 2 no lugar do 0 ele deixa 2
        PassageirosController pasCont = new PassageirosController();

        try {
            ArrayList<Passageiros> passageiros = pasCont.listarPassageiros(nome);
            passageiros.forEach((Passageiros passageiro) -> {
                tableModel.addRow(new Object[] {passageiro.getId(),passageiro.getNome(),
                    passageiro.getCpf(), passageiro.getTelefone()});

        });

        } catch (ExceptionDAO e) {

        }

    }//GEN-LAST:event_btnPesqPasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Tela_Principal tp = new Tela_Principal();
        tp.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblPassageiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPassageiroMouseClicked
        if (evt.getClickCount() == 1) {
            // abaixo vai pegar o valor que ta na coluna zero
            Integer passageiroId = (Integer) tblPassageiro.getModel().getValueAt(tblPassageiro.getSelectedRow(), 0);
            String nome = (String) tblPassageiro.getModel().getValueAt(tblPassageiro.getSelectedRow(), 1);
            String cpf = (String) tblPassageiro.getModel().getValueAt(tblPassageiro.getSelectedRow(), 2);
            Integer telefone = (Integer) tblPassageiro.getModel().getValueAt(tblPassageiro.getSelectedRow(), 3);

            this.telacadastrarpassageiros.buscarPassageiro(passageiroId, nome, cpf, telefone);
            this.telacadastrarpassageiros.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tblPassageiroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesqPas;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPassageiro;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
